package main

import (
	"fitai-backend/routes"
	"github.com/gofiber/fiber/v2"
	_ "fitai-backend/docs" // docs is generated by swag init; it contains the API documentation
	"github.com/gofiber/swagger"
	"github.com/joho/godotenv"
)

// @title FitAI API
// @version 1.0
// @description Backend for Personalized Diet & Workout Suggestions
// @host localhost:8080
// @BasePath /api

func main() {
	app := fiber.New()

	// Swagger documentation route
	app.Get("/swagger/*", swagger.HandlerDefault)

	//Register all routes
	routes.RegisterRoutes(app)

	app.Listen(":8080")

	err := godotenv.Load()
	if err != nil {
		log.Fatal("Error loading .env file")
	}
}